all:
        clang++ -I/Library/Frameworks/SDL2.framework/Headers -F/Library/Frameworks -framework SDL2 main.cpp -o main
all:        
        clang++ main.cpp -F/Library/Frameworks -framework SDL2 -F/Library/Frameworks -framework SDL2_image -I include -o main
